# Generated by Django 6.0.7 on 2026-07-31 06:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, default="", max_length=254
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=100)),
                (
                    "request_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("browser", models.CharField(blank=True, default="", max_length=100)),
                ("os", models.CharField(blank=True, default="", max_length=100)),
                (
                    "device_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "status",
                    models.CharField(db_index=True, default="SUCCESS", max_length=20),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_logs__action_70fdcf_idx",
                    ),
                    models.Index(
                        fields=["request_id"], name="audit_logs__request_0d533f_idx"
                    ),
                ],
            },
        ),
    ]
