# Generated by Django 6.0.7 on 2026-08-03 10:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.shelters.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shelter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255, verbose_name="shelter name")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="legal name",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="registration number",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="tax ID"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="shelter email"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=30, verbose_name="phone number"),
                ),
                (
                    "website",
                    models.URLField(blank=True, default="", verbose_name="website URL"),
                ),
                (
                    "address_line1",
                    models.CharField(max_length=255, verbose_name="address line 1"),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="address line 2",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="city"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="state / province"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="postal code"),
                ),
                (
                    "country",
                    models.CharField(
                        default="USA", max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shelters/logos/",
                        verbose_name="logo image",
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shelters/banners/",
                        verbose_name="banner image",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("verified", "Verified"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="unverified",
                        max_length=30,
                        verbose_name="shelter status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Designates whether this shelter is active on the platform.",
                        verbose_name="active status",
                    ),
                ),
            ],
            options={
                "verbose_name": "shelter",
                "verbose_name_plural": "shelters",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="shelters_sh_name_598a73_idx"),
                    models.Index(
                        fields=["city", "state"], name="shelters_sh_city_6c1638_idx"
                    ),
                    models.Index(
                        fields=["status", "is_active"],
                        name="shelters_sh_status_5c576b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShelterVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("needs_information", "Needs Information"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="verification status",
                    ),
                ),
                (
                    "reviewer_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal staff notes and observations regarding verification.",
                        verbose_name="reviewer notes",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Feedback provided to shelter if verification is rejected or needs information.",
                        verbose_name="rejection reason",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="submitted at"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reviewed at"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reviewed by staff user",
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="shelters.shelter",
                        verbose_name="shelter",
                    ),
                ),
            ],
            options={
                "verbose_name": "shelter verification",
                "verbose_name_plural": "shelter verifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShelterDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("registration_certificate", "Registration Certificate"),
                            ("ngo_certificate", "NGO Certificate"),
                            ("government_license", "Government License"),
                            ("address_proof", "Address Proof"),
                            ("identity_proof", "Identity Proof"),
                            ("tax_certificate", "Tax Certificate"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="document type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="shelters/documents/%Y/%m/",
                        validators=[
                            apps.shelters.validators.validate_document_file_size,
                            apps.shelters.validators.validate_document_mime_type,
                        ],
                        verbose_name="document file",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="original file name"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        help_text="File size in bytes",
                        verbose_name="file size in bytes",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="MIME type"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="document status",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="rejection reason"
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="shelters.shelter",
                        verbose_name="shelter",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by user",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="verified by staff user",
                    ),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="shelters.shelterverification",
                        verbose_name="associated verification workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "shelter document",
                "verbose_name_plural": "shelter documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShelterInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="invited email"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("staff", "Staff"),
                            ("volunteer", "Volunteer"),
                        ],
                        default="volunteer",
                        max_length=30,
                        verbose_name="invited role",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="invitation token",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="invitation status",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="accepted at"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="expires at"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="responded at"
                    ),
                ),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_shelter_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="accepted by user",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_shelter_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invited by user",
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="shelters.shelter",
                        verbose_name="shelter",
                    ),
                ),
            ],
            options={
                "verbose_name": "shelter invitation",
                "verbose_name_plural": "shelter invitations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["token", "status"], name="shelters_sh_token_2f49d4_idx"
                    ),
                    models.Index(
                        fields=["shelter", "status"],
                        name="shelters_sh_shelter_7262e7_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("shelter", "email"),
                        name="unique_pending_shelter_invitation",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ShelterMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("staff", "Staff"),
                            ("volunteer", "Volunteer"),
                        ],
                        db_index=True,
                        default="volunteer",
                        max_length=30,
                        verbose_name="membership role",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Designates whether this user membership is currently active.",
                        verbose_name="active status",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="joined at"),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="shelters.shelter",
                        verbose_name="shelter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user account associated with this shelter membership.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelter_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "shelter member",
                "verbose_name_plural": "shelter members",
                "ordering": ["-joined_at"],
                "indexes": [
                    models.Index(
                        fields=["shelter", "role"],
                        name="shelters_sh_shelter_2c9667_idx",
                    ),
                    models.Index(
                        fields=["shelter", "is_active"],
                        name="shelters_sh_shelter_bde52a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "shelter"),
                        name="unique_shelter_user_membership",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="shelterverification",
            index=models.Index(
                fields=["shelter", "status"], name="shelters_sh_shelter_1f2938_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shelterverification",
            index=models.Index(
                fields=["status", "submitted_at"], name="shelters_sh_status_58335c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shelterverification",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["draft", "submitted", "under_review", "needs_information"],
                    )
                ),
                fields=("shelter",),
                name="unique_active_shelter_verification",
            ),
        ),
        migrations.AddIndex(
            model_name="shelterdocument",
            index=models.Index(
                fields=["shelter", "document_type"],
                name="shelters_sh_shelter_1ea1b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shelterdocument",
            index=models.Index(
                fields=["verification", "status"], name="shelters_sh_verific_4cd87e_idx"
            ),
        ),
    ]
