# Generated by Django 6.0.7 on 2026-08-07 05:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShelterAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address_line1",
                    models.CharField(max_length=255, verbose_name="address line 1"),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="address line 2",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="city"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="state / province"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="USA", max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True, verbose_name="is primary address"
                    ),
                ),
            ],
            options={
                "verbose_name": "shelter address",
                "verbose_name_plural": "shelter addresses",
                "ordering": ["city", "state"],
            },
        ),
        migrations.AddField(
            model_name="shelter",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("non_profit", "Non-Profit / NGO"),
                    ("municipal", "Municipal / Government Shelter"),
                    ("private", "Private Rescue / Sanctuary"),
                    ("foster_network", "Foster Network"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="non_profit",
                max_length=50,
                verbose_name="organization type",
            ),
        ),
        migrations.AddIndex(
            model_name="shelter",
            index=models.Index(
                fields=["organization_type"], name="shelters_sh_organiz_8af27f_idx"
            ),
        ),
        migrations.AddField(
            model_name="shelteraddress",
            name="shelter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address_rel",
                to="shelters.shelter",
                verbose_name="shelter",
            ),
        ),
        migrations.AddIndex(
            model_name="shelteraddress",
            index=models.Index(
                fields=["city", "state"], name="shelters_sh_city_f81d9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shelteraddress",
            index=models.Index(
                fields=["postal_code"], name="shelters_sh_postal__c4cb87_idx"
            ),
        ),
    ]
