# Generated by Django 6.0.7 on 2026-08-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0002_shelteraddress_shelter_organization_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelterinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("staff", "Staff"),
                    ("volunteer", "Volunteer"),
                    ("veterinarian", "Veterinarian"),
                    ("viewer", "Viewer"),
                ],
                default="volunteer",
                max_length=30,
                verbose_name="invited role",
            ),
        ),
        migrations.AlterField(
            model_name="sheltermember",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("staff", "Staff"),
                    ("volunteer", "Volunteer"),
                    ("veterinarian", "Veterinarian"),
                    ("viewer", "Viewer"),
                ],
                db_index=True,
                default="volunteer",
                max_length=30,
                verbose_name="membership role",
            ),
        ),
    ]
