# Generated by Django 6.0.7 on 2026-07-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/profile_images/",
                verbose_name="profile image",
            ),
        ),
    ]
