# Generated by Django 6.0.7 on 2026-07-31 07:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_emailverificationtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token_hash",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="token hash"
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("EMAIL_VERIFICATION", "Email Verification"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("EMAIL_CHANGE", "Email Change"),
                            ("ACCOUNT_INVITATION", "Account Invitation"),
                        ],
                        db_index=True,
                        default="EMAIL_VERIFICATION",
                        max_length=32,
                        verbose_name="token type",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="expires at"),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="used at"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="is active"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
            ],
            options={
                "verbose_name": "account token",
                "verbose_name_plural": "account tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="emailverificationtoken",
            name="accounts_em_token_h_795ad6_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailverificationtoken",
            name="accounts_em_expires_f36bd3_idx",
        ),
        migrations.AddField(
            model_name="accounttoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="emailverificationtoken",
            name="user",
        ),
        migrations.AddIndex(
            model_name="accounttoken",
            index=models.Index(
                fields=["token_hash"], name="accounts_ac_token_h_ad3903_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accounttoken",
            index=models.Index(
                fields=["token_type", "is_active"],
                name="accounts_ac_token_t_2adb79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accounttoken",
            index=models.Index(
                fields=["expires_at"], name="accounts_ac_expires_c6ddfb_idx"
            ),
        ),
        migrations.DeleteModel(
            name="EmailVerificationToken",
        ),
    ]
