# Generated by Django 6.0.7 on 2026-07-31 07:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_accounttoken_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users/avatars/",
                        verbose_name="avatar image",
                    ),
                ),
                ("bio", models.TextField(blank=True, default="", verbose_name="bio")),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        blank=True,
                        default=apps.accounts.models.profile.default_profile_preferences,
                        verbose_name="user preferences",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
